#!/usr/bin/env ruby

# Takes comments.yml generated by wordpressxml2jekyll.rb and posts them to your Disqus forum.
# uses original WordPress post id as disqus_identifier
# the user key for Disqus must be stored on API-KEY file
# Disqus ruby api http://disqus.rubyforge.org/
# sudo gem install disqus

require 'rubygems'
require 'disqus'
require 'disqus/api'
require 'yaml'


COMMENTS_YAML_FILE = "#{ENV['PWD']}/export/_posts/comments.yml"

file = File.open("API-KEY", "rb")
apikey = file.read
p "Using API-KEY: #{apikey}"
Disqus::defaults[:api_key] = apikey

forum_id = Disqus::Api.get_forum_list["message"].first["id"]
fak = Disqus::Api.get_forum_api_key(:forum_id => forum_id)["message"]

File.open(COMMENTS_YAML_FILE) do |yf|
  YAML.each_document( yf ) do |c|
    post_id = c.ivars["post_id"]
    post_title = c.ivars["post_title"]
    
    puts "post_id: #{post_id}"
    puts "post_title: #{post_title}"
    
    thread = Disqus::Api.thread_by_identifier(:forum_api_key => fak, :title => post_title, :identifier => post_id)
    
    puts "======= thread_by_identifier result BEGIN ====="
    thread.each { |k,v| puts "#{k} => #{v}" }
    puts "======= thread_by_identifier result END ====="

    thread_id = thread["message"]["thread"]["id"]
    p "thread id: #{thread_id}\n\n"
    comment = Disqus::Api.create_post(:forum_api_key => fak,
                            :thread_id => thread_id,
                            :message => c.ivars["content"],
                            :author_name => c.ivars["author_name"],
                            :author_email => c.ivars["author_email"],
                            :author_url => c.ivars["author_url"],
                            :created_at => Time.parse(c.ivars["created_at"].to_s).strftime("%Y-%m-%dT%H:%M"))
    puts "======= create_post result BEGIN ====="
    comment.each { |k,v| puts "#{k} => #{v}" }
    puts "======= create_post result END ====="
  end
end
